### ISSUE TITLE
Samples are out of date

### ISSUE THREAD

**Issue by tychedelia** [TouchDesigner/CustomOperatorSamples#6]
Warning to others: Samples here are dangerously out of date. Make sure to use the headers included in the TD install directory instead, which include a number of significant breaking changes. Just wasted so much time developing against these 😭.

**Comment by mbechard** [comment]
Yeah, very sorry, we are actively working on updating them right now.

**Comment by tychedelia** [comment]
> Yeah, very sorry, we are actively working on updating them right now.

Sorry, I was being a bit of a grumpy baby last night. The API improvements are in general very nice and much appreciated.

**Comment by charliewilliams** [comment]
Love you guys but this is still an open issue :)

**Comment by VaradDerivative** [comment]
hey Charlie, it's fixed for 2023.10k now. Thanks for your report.
